### ISSUE TITLE
[Feature]: DBのカラム追加

### ISSUE THREAD

**Issue by notchcoder** [Dev-roll/couponroll#2]
### リクエストの内容

- DBに必要なカラムを追加する

### Todo

- [x] `stores`に`img_url varchar(255)`を追加
- [x] `stores`の`icon`を`icon_url varchar(255)`に変更
- [x] `coupons`に`img_url varchar(255)`を追加
- [x] `coupons`に`discount int`を追加
